// <auto-generated />
namespace teste.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dataexpedicaoCliente11122017AlanNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataexpedicaoCliente11122017AlanNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111759002_dataexpedicaoCliente 11122017 - Alan Note"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
