// <auto-generated />
namespace teste.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class documentos16122017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentos16122017));
        
        string IMigrationMetadata.Id
        {
            get { return "201712162105347_documentos 16122017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
