// <auto-generated />
namespace teste.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Venda_Produto_Jogo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Venda_Produto_Jogo));
        
        string IMigrationMetadata.Id
        {
            get { return "201801282115461_Venda_Produto_Jogo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
